- collections.sh
Removed tricy_scan.sh from docker_publish incollection.sh 
[CLOUD-440](https://usxtech.atlassian.net/browse/CLOUD-440)
- in hand with https://github.com/variant-inc/actions-dotnet/pull/16
> [CLOUD-440] removed trivy_scan.sh

- scripts/publish.sh
Adding image name output parameter
Fixes [#9](https://usxtech.atlassian.net/browse/CLOUD-314)
This has been tested by demo app, pointing to the actions octopus branch and action-dotnet branch.
> adding image name output parameter

- scripts/publish.sh
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes [#8](https://usxtech.atlassian.net/browse/CLOUD-8)
```text
```
> [CLOUD-554] del nuget push

- scripts/publish.sh
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
https://github.com/variant-inc/replicator/runs/3488741999?check_suite_focus=true
This is using pythons action which is currently pointing to v0 tag of actions collection. Once this is merged it will be promoted to v1
> Fix for loop

- scripts/publish.sh
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes [#8](https://usxtech.atlassian.net/browse/CLOUD-8)
```text
```
> [SETX] Add set-x

- scripts/publish.sh
Iterate over env variables in file instead of directly via process substitution 
```text
```
Debian/Python
https://github.com/variant-inc/replicator/runs/3556651694?check_suite_focus=true#step:5:1219
Alpine/NodeJS
https://github.com/variant-inc/demo-nodejs-app/runs/3556656823?check_suite_focus=true#step:5:982
Build failing due to trivy scan
Alpine/Dotnet
https://github.com/variant-inc/demo-app/runs/3556940353?check_suite_focus=true
> [ENV] tee env to txt and set build args from txt

- .github/linters/actionlint.yaml
- .github/workflows/lint.yaml
- scripts/ecr_create.sh
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes [#1267](https://drivevariant.atlassian.net/browse/CLOUD-1267)
Awaiting: https://drivevariant.atlassian.net/browse/CLOUD-1266
- Create dummy branch in actions-nodejs, actions-dotnet that uses this branch of actions-collection
- Run in demo-app
> [CLOUD-1267] updated endpoint

- scripts/ecr_create.sh
Fix request body to include new environment name. 
prod -> production
```text
```
> Fix profile enum typo

- scripts/enable_sonar.ps1
Log cleanup
Fixes [#8](https://usxtech.atlassian.net/browse/CLOUD-8)
```text
```
> logs cleanup

- scripts/publish.ps1
Fix the way we export image name in actions-collections
Fixes [#1740](https://usxtech.atlassian.net/browse/CLOUD-1740)
```text
Tested with demo-python-flask-api
CI Run:
https://github.com/variant-inc/demo-python-flask-variant-api/runs/7064697066?check_suite_focus=true
Octopus deployment:
https://octopus.apps.ops-drivevariant.com/app#/Spaces-2/projects/demo-api-lee/deployments/releases/0.1.0-demo-lee0001.208/deployments/Deployments-40447?activeTab=taskSummary
```
> Fix image name issue

- scripts/enable_sonar.ps1
Please refer to the ticket for details
Fixes [#8]()
https://drivevariant.atlassian.net/browse/CLOUD-1855
This has been tested using the demo projects for python, DotNet, NodeJs. All of the details about the test cases has been mentioned in the comments of the ticket mentioned above
> CLOUD-1855: Changes for Sonar projectKey and projectName

- scripts/pre_test.sh
Adding safe directory in git config
> add safe directory for git

- build-push-image/build-push-core/action.yml
https://github.com/variant-inc/demo-python-flask-variant-api/actions/runs/5049070002
https://github.com/variant-inc/demo-python-flask-variant-api/actions/runs/5049070002/attempts/2
> [ADD] add summary

- sonar-coverage-check/action.yml
Remove if and move it to actions-python/nodejs/dotnet
Please describe the tests that you ran to verify your changes.
Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration
> [CLOUD-2321] fix: remove if from action

- build-push-image/ecr_create.sh
Add retries while fetching ECR repo and creating new one via Lazy API.
Test run with this branch of action.
https://github.com/variant-inc/sample-dotnet-api/actions/runs/9906806383/job/27369153510
> fix: add curl retry

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- build-push-image/action.yml
- build-push-image/check_tag_exists.sh
- build-push-image/ecr_create.sh
- scripts/action-docs.sh
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context.
List any dependencies that are required for this change.
Fixes [#2561](https://usxpress.atlassian.net/browse/CLOUD-2485)
Test Cases :- 
https://github.com/variant-inc/demo-python-flask-variant-api/actions/runs/11012977747/job/30583697648
https://octopus.usxpress.io/app#/Spaces-2/projects/test-user-parul-2/deployments/releases/0.2.0-feature-test-bui0126.1212/deployments/Deployments-72575?activeTab=taskLog&level=verbose
More Tests:
https://octopus.usxpress.io/app#/Spaces-2/projects/test-user-parul-2/deployments/releases/0.2.0-feature-test-bui0165.1328/deployments/Deployments-75083
https://github.com/variant-inc/demo-python-flask-variant-api/actions/runs/11917292749/job/332120 …
> [CLOUD-2611] feat: separate ECR for feature & release for DX apps

- .github/workflows/release.yml
- GitVersion.yml
Fix: revert back to checkout instead of actions-setup
Please describe the tests that you ran to verify your changes.
Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration
> fix: revert to manual actions

- build-push-image/action.yml
Fixes [#2313](https://usxpress.atlassian.net/browse/CLOUD-2313)
https://github.com/variant-inc/demo-python-flask-variant-api/actions/runs/12596811200/job/35110272960
> use TRIVY_S3_BUCKET env

- .github/workflows/release.yml
fix Git version spec input
https://github.com/variant-inc/actions-collection/actions/runs/12628513915/job/35184754616
> fix git version

- build-push-image/ecr_create.sh
Removed verbose from ecr create curl call to lazy go 
https://github.com/variant-inc/demo-python-flask-variant-api/actions/runs/12874626107/job/35894405277
Please describe the tests that you ran to verify your changes.
Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration
> Removed verbose from ecr create curl call to lazy go
